### PR TITLE
Apply consistent formatting, clean up code

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR provides the editor hints needed to get everyone on the same page with indentation and line endings and applies standardized formatting to the source files.
- Use Tabs with 4 column width.
- Use Windows CRLF line endings.
- Use the "One True Brace" style for opening braces.
- Use visible `\t` for tabs inside `printf` statements.

### Code refactors
- Add a `BOOL` type and apply to some functions.
- Capitalize 6502 assembler directives.
- Add `asm_printf`, `a`, `ap` for formatted asm output lines.
- Branch functions share a common function.

### CODE REVIEW

**Comment by msaarna** [comment]
merged. Thanks!

**Comment by thinkyhead** [comment]
Great. Let me know if you see any issues with the compiled result.
I tested it with the Zombie Crash demo code and it seemed okay.

**Comment by msaarna** [comment]
I've been tracking down a few bugs that were introduced with this merge, though there's still a few outstanding. I've attached a basic listing, and the same list file generated from the master and v1.5... 

[referencecore.bas.v1.5.txt](https://github.com/batari-Basic/batari-Basic/files/5744077/referencecore.bas.v1.5.txt)
[referencecore.bas.txt](https://github.com/batari-Basic/batari-Basic/files/5744078/referencecore.bas.txt)
[referencecore.bas.master.txt](https://github.com/batari-Basic/batari-Basic/files/5744079/referencecore.bas.master.txt)

If you search both listings for "if...then" you can see the previous rev and your cleaned up one start to drift right at that section.

I like what you've done for the cleanup quite a bit, so I've been at it tracking down and fixing some introduced bugs for the last couple days. But I only have so much hobby time, and I don't want to leave the project broken much longer. At some point I may have to cut bait and revert the merge.

**Comment by thinkyhead** [comment]
Thanks for the note. It's been a while since I've had time to work on this. If the changes were too much at once, it's understandable, and it's better to have reverted. I will submit patches in smaller pieces so they are easier to track.

**Pull request merged**
